### ISSUE TITLE
Contains on M2M models produces same result multiple times

### ISSUE THREAD

**Issue by twang817** [ivelum/djangoql#85]
I don't know if this is expected behavior:

```
class Author(models.Model):
    name = models.CharField(max_length=50)
    books = models.ManyToManyField(Book)

class Book(model.Model):
    name = models.CharField(max_length=50)

@admin.register(Author)
class AuthorAdmin(DjangoQLSearchMixin, admin.ModelAdmin):
    pass
```

Even if I only have a single author with multiple books, when using the search query:

```
books.name ~ "The"
```

I get the same author listed multiple times in the change_list view of the admin site.

**Comment by stebunovd** [comment]
hey @twang817,

I guess you should just add ``.distinct()`` to the generated query and you should be fine. You can do so by overriding the ``.get_queryset()`` method, like this:

```python
...

@admin.register(Author)
class AuthorAdmin(DjangoQLSearchMixin, admin.ModelAdmin):
    def get_queryset(self, request):
        return super().get_queryset(request).distinct()
```

DjangoQL doesn't add it for you automatically, because it cannot determine in which situations it might be necessary, but you can always do it yourself. I hope that helps.


Thanks,

Denis
